// Har country ki poori configuration ek jagah — Configuration-Driven Design
// Nayi country ya ID document add karna ho to SIRF is file mein change karo.

// National ID document ki info — jo countries apna ID card use karti hain
// KYC rule: Passport HAR country ke liye option hai;
// agar nationalId != null to user ko choice milegi: National ID ya Passport
class NationalIdDoc {
  final String name; // CNIC, Aadhaar, Emirates ID...
  final String hint; // format hint user ke liye

  const NationalIdDoc(this.name, [this.hint = 'ID number']);
}

class CountryConfig {
  final String name;
  final String isoCode; // PK, DE, US — international standard (ISO 3166-1)
  final String dialCode; // +92, +49, +1
  final NationalIdDoc? nationalId; // null = sirf Passport se KYC hogi

  const CountryConfig({
    required this.name,
    required this.isoCode,
    required this.dialCode,
    this.nationalId,
  });

  // Flag emoji ISO code se ban jata hai — data likhne ki zaroorat nahi
  // (A-Z letters ko Unicode "regional indicator" symbols mein convert karo)
  String get flag => isoCode
      .toUpperCase()
      .codeUnits
      .map((c) => String.fromCharCode(0x1F1E6 + c - 65))
      .join();

  // KYC ke liye available documents — Passport hamesha, National ID agar hai
  List<String> get kycDocuments =>
      [if (nationalId != null) nationalId!.name, 'Passport'];
}

// Duniya ke tamam countries — alphabetically sorted
const List<CountryConfig> allCountries = [
  CountryConfig(name: 'Afghanistan', isoCode: 'AF', dialCode: '+93', nationalId: NationalIdDoc('Tazkira')),
  CountryConfig(name: 'Albania', isoCode: 'AL', dialCode: '+355', nationalId: NationalIdDoc('Letërnjoftim (ID Card)')),
  CountryConfig(name: 'Algeria', isoCode: 'DZ', dialCode: '+213', nationalId: NationalIdDoc('CNIBE (National ID)')),
  CountryConfig(name: 'Andorra', isoCode: 'AD', dialCode: '+376'),
  CountryConfig(name: 'Angola', isoCode: 'AO', dialCode: '+244', nationalId: NationalIdDoc('Bilhete de Identidade')),
  CountryConfig(name: 'Antigua and Barbuda', isoCode: 'AG', dialCode: '+1268'),
  CountryConfig(name: 'Argentina', isoCode: 'AR', dialCode: '+54', nationalId: NationalIdDoc('DNI', '12.345.678')),
  CountryConfig(name: 'Armenia', isoCode: 'AM', dialCode: '+374', nationalId: NationalIdDoc('ID Card')),
  CountryConfig(name: 'Australia', isoCode: 'AU', dialCode: '+61'),
  CountryConfig(name: 'Austria', isoCode: 'AT', dialCode: '+43', nationalId: NationalIdDoc('Personalausweis')),
  CountryConfig(name: 'Azerbaijan', isoCode: 'AZ', dialCode: '+994', nationalId: NationalIdDoc('ID Card')),
  CountryConfig(name: 'Bahamas', isoCode: 'BS', dialCode: '+1242'),
  CountryConfig(name: 'Bahrain', isoCode: 'BH', dialCode: '+973', nationalId: NationalIdDoc('CPR Card', '123456789')),
  CountryConfig(name: 'Bangladesh', isoCode: 'BD', dialCode: '+880', nationalId: NationalIdDoc('NID', '1234567890')),
  CountryConfig(name: 'Barbados', isoCode: 'BB', dialCode: '+1246', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Belarus', isoCode: 'BY', dialCode: '+375', nationalId: NationalIdDoc('ID Card')),
  CountryConfig(name: 'Belgium', isoCode: 'BE', dialCode: '+32', nationalId: NationalIdDoc('eID Card')),
  CountryConfig(name: 'Belize', isoCode: 'BZ', dialCode: '+501'),
  CountryConfig(name: 'Benin', isoCode: 'BJ', dialCode: '+229', nationalId: NationalIdDoc('CNI')),
  CountryConfig(name: 'Bhutan', isoCode: 'BT', dialCode: '+975', nationalId: NationalIdDoc('Citizenship ID')),
  CountryConfig(name: 'Bolivia', isoCode: 'BO', dialCode: '+591', nationalId: NationalIdDoc('Cédula de Identidad')),
  CountryConfig(name: 'Bosnia and Herzegovina', isoCode: 'BA', dialCode: '+387', nationalId: NationalIdDoc('Lična karta (ID Card)')),
  CountryConfig(name: 'Botswana', isoCode: 'BW', dialCode: '+267', nationalId: NationalIdDoc('Omang')),
  CountryConfig(name: 'Brazil', isoCode: 'BR', dialCode: '+55', nationalId: NationalIdDoc('CPF', '123.456.789-09')),
  CountryConfig(name: 'Brunei', isoCode: 'BN', dialCode: '+673', nationalId: NationalIdDoc('IC Card')),
  CountryConfig(name: 'Bulgaria', isoCode: 'BG', dialCode: '+359', nationalId: NationalIdDoc('Lichna karta (ID Card)')),
  CountryConfig(name: 'Burkina Faso', isoCode: 'BF', dialCode: '+226', nationalId: NationalIdDoc('CNIB')),
  CountryConfig(name: 'Burundi', isoCode: 'BI', dialCode: '+257', nationalId: NationalIdDoc('CNI')),
  CountryConfig(name: 'Cabo Verde', isoCode: 'CV', dialCode: '+238', nationalId: NationalIdDoc('CNI')),
  CountryConfig(name: 'Cambodia', isoCode: 'KH', dialCode: '+855', nationalId: NationalIdDoc('Khmer ID Card')),
  CountryConfig(name: 'Cameroon', isoCode: 'CM', dialCode: '+237', nationalId: NationalIdDoc('CNI')),
  CountryConfig(name: 'Canada', isoCode: 'CA', dialCode: '+1'),
  CountryConfig(name: 'Central African Republic', isoCode: 'CF', dialCode: '+236'),
  CountryConfig(name: 'Chad', isoCode: 'TD', dialCode: '+235', nationalId: NationalIdDoc('CNI')),
  CountryConfig(name: 'Chile', isoCode: 'CL', dialCode: '+56', nationalId: NationalIdDoc('Cédula (RUT)', '12.345.678-9')),
  CountryConfig(name: 'China', isoCode: 'CN', dialCode: '+86', nationalId: NationalIdDoc('Resident ID Card', '123456789012345678')),
  CountryConfig(name: 'Colombia', isoCode: 'CO', dialCode: '+57', nationalId: NationalIdDoc('Cédula de Ciudadanía', '1234567890')),
  CountryConfig(name: 'Comoros', isoCode: 'KM', dialCode: '+269'),
  CountryConfig(name: 'Congo (Brazzaville)', isoCode: 'CG', dialCode: '+242'),
  CountryConfig(name: 'Congo (DRC)', isoCode: 'CD', dialCode: '+243', nationalId: NationalIdDoc('Carte d\'identité')),
  CountryConfig(name: 'Costa Rica', isoCode: 'CR', dialCode: '+506', nationalId: NationalIdDoc('Cédula', '1-2345-6789')),
  CountryConfig(name: 'Croatia', isoCode: 'HR', dialCode: '+385', nationalId: NationalIdDoc('Osobna iskaznica (ID Card)')),
  CountryConfig(name: 'Cuba', isoCode: 'CU', dialCode: '+53', nationalId: NationalIdDoc('Carné de Identidad')),
  CountryConfig(name: 'Cyprus', isoCode: 'CY', dialCode: '+357', nationalId: NationalIdDoc('ID Card')),
  CountryConfig(name: 'Czechia', isoCode: 'CZ', dialCode: '+420', nationalId: NationalIdDoc('Občanský průkaz (ID Card)')),
  CountryConfig(name: 'Denmark', isoCode: 'DK', dialCode: '+45'),
  CountryConfig(name: 'Djibouti', isoCode: 'DJ', dialCode: '+253', nationalId: NationalIdDoc('CNI')),
  CountryConfig(name: 'Dominica', isoCode: 'DM', dialCode: '+1767'),
  CountryConfig(name: 'Dominican Republic', isoCode: 'DO', dialCode: '+1809', nationalId: NationalIdDoc('Cédula', '123-4567890-1')),
  CountryConfig(name: 'Ecuador', isoCode: 'EC', dialCode: '+593', nationalId: NationalIdDoc('Cédula', '1234567890')),
  CountryConfig(name: 'Egypt', isoCode: 'EG', dialCode: '+20', nationalId: NationalIdDoc('National ID', '12345678901234')),
  CountryConfig(name: 'El Salvador', isoCode: 'SV', dialCode: '+503', nationalId: NationalIdDoc('DUI', '12345678-9')),
  CountryConfig(name: 'Equatorial Guinea', isoCode: 'GQ', dialCode: '+240'),
  CountryConfig(name: 'Eritrea', isoCode: 'ER', dialCode: '+291'),
  CountryConfig(name: 'Estonia', isoCode: 'EE', dialCode: '+372', nationalId: NationalIdDoc('ID-kaart')),
  CountryConfig(name: 'Eswatini', isoCode: 'SZ', dialCode: '+268'),
  CountryConfig(name: 'Ethiopia', isoCode: 'ET', dialCode: '+251', nationalId: NationalIdDoc('Fayda ID')),
  CountryConfig(name: 'Fiji', isoCode: 'FJ', dialCode: '+679'),
  CountryConfig(name: 'Finland', isoCode: 'FI', dialCode: '+358', nationalId: NationalIdDoc('Henkilökortti (ID Card)')),
  CountryConfig(name: 'France', isoCode: 'FR', dialCode: '+33', nationalId: NationalIdDoc('CNI (Carte d\'identité)')),
  CountryConfig(name: 'Gabon', isoCode: 'GA', dialCode: '+241'),
  CountryConfig(name: 'Gambia', isoCode: 'GM', dialCode: '+220', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Georgia', isoCode: 'GE', dialCode: '+995', nationalId: NationalIdDoc('ID Card')),
  CountryConfig(name: 'Germany', isoCode: 'DE', dialCode: '+49', nationalId: NationalIdDoc('Personalausweis', 'L01X00T47')),
  CountryConfig(name: 'Ghana', isoCode: 'GH', dialCode: '+233', nationalId: NationalIdDoc('Ghana Card', 'GHA-123456789-0')),
  CountryConfig(name: 'Greece', isoCode: 'GR', dialCode: '+30', nationalId: NationalIdDoc('Taftotita (ID Card)')),
  CountryConfig(name: 'Grenada', isoCode: 'GD', dialCode: '+1473'),
  CountryConfig(name: 'Guatemala', isoCode: 'GT', dialCode: '+502', nationalId: NationalIdDoc('DPI', '1234 56789 0101')),
  CountryConfig(name: 'Guinea', isoCode: 'GN', dialCode: '+224'),
  CountryConfig(name: 'Guinea-Bissau', isoCode: 'GW', dialCode: '+245'),
  CountryConfig(name: 'Guyana', isoCode: 'GY', dialCode: '+592', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Haiti', isoCode: 'HT', dialCode: '+509', nationalId: NationalIdDoc('CIN')),
  CountryConfig(name: 'Honduras', isoCode: 'HN', dialCode: '+504', nationalId: NationalIdDoc('DNI', '1234-5678-90123')),
  CountryConfig(name: 'Hong Kong', isoCode: 'HK', dialCode: '+852', nationalId: NationalIdDoc('HKID', 'A123456(7)')),
  CountryConfig(name: 'Hungary', isoCode: 'HU', dialCode: '+36', nationalId: NationalIdDoc('Személyi igazolvány (ID Card)')),
  CountryConfig(name: 'Iceland', isoCode: 'IS', dialCode: '+354'),
  CountryConfig(name: 'India', isoCode: 'IN', dialCode: '+91', nationalId: NationalIdDoc('Aadhaar', '1234 5678 9012')),
  CountryConfig(name: 'Indonesia', isoCode: 'ID', dialCode: '+62', nationalId: NationalIdDoc('KTP (NIK)', '1234567890123456')),
  CountryConfig(name: 'Iran', isoCode: 'IR', dialCode: '+98', nationalId: NationalIdDoc('National ID Card', '1234567890')),
  CountryConfig(name: 'Iraq', isoCode: 'IQ', dialCode: '+964', nationalId: NationalIdDoc('National Card')),
  CountryConfig(name: 'Ireland', isoCode: 'IE', dialCode: '+353'),
  CountryConfig(name: 'Israel', isoCode: 'IL', dialCode: '+972', nationalId: NationalIdDoc('Teudat Zehut', '123456789')),
  CountryConfig(name: 'Italy', isoCode: 'IT', dialCode: '+39', nationalId: NationalIdDoc('Carta d\'Identità', 'CA12345AA')),
  CountryConfig(name: 'Ivory Coast', isoCode: 'CI', dialCode: '+225', nationalId: NationalIdDoc('CNI')),
  CountryConfig(name: 'Jamaica', isoCode: 'JM', dialCode: '+1876', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Japan', isoCode: 'JP', dialCode: '+81', nationalId: NationalIdDoc('My Number Card', '1234 5678 9012')),
  CountryConfig(name: 'Jordan', isoCode: 'JO', dialCode: '+962', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Kazakhstan', isoCode: 'KZ', dialCode: '+7', nationalId: NationalIdDoc('ID Card (IIN)', '123456789012')),
  CountryConfig(name: 'Kenya', isoCode: 'KE', dialCode: '+254', nationalId: NationalIdDoc('National ID', '12345678')),
  CountryConfig(name: 'Kiribati', isoCode: 'KI', dialCode: '+686'),
  CountryConfig(name: 'Kuwait', isoCode: 'KW', dialCode: '+965', nationalId: NationalIdDoc('Civil ID', '123456789012')),
  CountryConfig(name: 'Kyrgyzstan', isoCode: 'KG', dialCode: '+996', nationalId: NationalIdDoc('ID Card')),
  CountryConfig(name: 'Laos', isoCode: 'LA', dialCode: '+856', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Latvia', isoCode: 'LV', dialCode: '+371', nationalId: NationalIdDoc('eID Card')),
  CountryConfig(name: 'Lebanon', isoCode: 'LB', dialCode: '+961', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Lesotho', isoCode: 'LS', dialCode: '+266', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Liberia', isoCode: 'LR', dialCode: '+231', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Libya', isoCode: 'LY', dialCode: '+218', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Liechtenstein', isoCode: 'LI', dialCode: '+423'),
  CountryConfig(name: 'Lithuania', isoCode: 'LT', dialCode: '+370', nationalId: NationalIdDoc('ID Card')),
  CountryConfig(name: 'Luxembourg', isoCode: 'LU', dialCode: '+352', nationalId: NationalIdDoc('ID Card')),
  CountryConfig(name: 'Macao', isoCode: 'MO', dialCode: '+853', nationalId: NationalIdDoc('BIR (Resident ID)')),
  CountryConfig(name: 'Madagascar', isoCode: 'MG', dialCode: '+261', nationalId: NationalIdDoc('CNI')),
  CountryConfig(name: 'Malawi', isoCode: 'MW', dialCode: '+265', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Malaysia', isoCode: 'MY', dialCode: '+60', nationalId: NationalIdDoc('MyKad', '123456-78-9012')),
  CountryConfig(name: 'Maldives', isoCode: 'MV', dialCode: '+960', nationalId: NationalIdDoc('National ID', 'A123456')),
  CountryConfig(name: 'Mali', isoCode: 'ML', dialCode: '+223', nationalId: NationalIdDoc('NINA Card')),
  CountryConfig(name: 'Malta', isoCode: 'MT', dialCode: '+356', nationalId: NationalIdDoc('ID Card')),
  CountryConfig(name: 'Marshall Islands', isoCode: 'MH', dialCode: '+692'),
  CountryConfig(name: 'Mauritania', isoCode: 'MR', dialCode: '+222', nationalId: NationalIdDoc('CNI')),
  CountryConfig(name: 'Mauritius', isoCode: 'MU', dialCode: '+230', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Mexico', isoCode: 'MX', dialCode: '+52', nationalId: NationalIdDoc('INE Card')),
  CountryConfig(name: 'Micronesia', isoCode: 'FM', dialCode: '+691'),
  CountryConfig(name: 'Moldova', isoCode: 'MD', dialCode: '+373', nationalId: NationalIdDoc('ID Card')),
  CountryConfig(name: 'Monaco', isoCode: 'MC', dialCode: '+377'),
  CountryConfig(name: 'Mongolia', isoCode: 'MN', dialCode: '+976', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Montenegro', isoCode: 'ME', dialCode: '+382', nationalId: NationalIdDoc('Lična karta (ID Card)')),
  CountryConfig(name: 'Morocco', isoCode: 'MA', dialCode: '+212', nationalId: NationalIdDoc('CNIE', 'A123456')),
  CountryConfig(name: 'Mozambique', isoCode: 'MZ', dialCode: '+258', nationalId: NationalIdDoc('Bilhete de Identidade')),
  CountryConfig(name: 'Myanmar', isoCode: 'MM', dialCode: '+95', nationalId: NationalIdDoc('NRC Card')),
  CountryConfig(name: 'Namibia', isoCode: 'NA', dialCode: '+264', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Nauru', isoCode: 'NR', dialCode: '+674'),
  CountryConfig(name: 'Nepal', isoCode: 'NP', dialCode: '+977', nationalId: NationalIdDoc('Citizenship Certificate')),
  CountryConfig(name: 'Netherlands', isoCode: 'NL', dialCode: '+31', nationalId: NationalIdDoc('ID-kaart')),
  CountryConfig(name: 'New Zealand', isoCode: 'NZ', dialCode: '+64'),
  CountryConfig(name: 'Nicaragua', isoCode: 'NI', dialCode: '+505', nationalId: NationalIdDoc('Cédula', '123-456789-0123A')),
  CountryConfig(name: 'Niger', isoCode: 'NE', dialCode: '+227', nationalId: NationalIdDoc('CNI')),
  CountryConfig(name: 'Nigeria', isoCode: 'NG', dialCode: '+234', nationalId: NationalIdDoc('NIN', '12345678901')),
  CountryConfig(name: 'North Korea', isoCode: 'KP', dialCode: '+850'),
  CountryConfig(name: 'North Macedonia', isoCode: 'MK', dialCode: '+389', nationalId: NationalIdDoc('Lična karta (ID Card)')),
  CountryConfig(name: 'Norway', isoCode: 'NO', dialCode: '+47', nationalId: NationalIdDoc('National ID Card')),
  CountryConfig(name: 'Oman', isoCode: 'OM', dialCode: '+968', nationalId: NationalIdDoc('Resident/ID Card')),
  CountryConfig(name: 'Pakistan', isoCode: 'PK', dialCode: '+92', nationalId: NationalIdDoc('CNIC', '12345-1234567-1')),
  CountryConfig(name: 'Palau', isoCode: 'PW', dialCode: '+680'),
  CountryConfig(name: 'Palestine', isoCode: 'PS', dialCode: '+970', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Panama', isoCode: 'PA', dialCode: '+507', nationalId: NationalIdDoc('Cédula', '8-123-4567')),
  CountryConfig(name: 'Papua New Guinea', isoCode: 'PG', dialCode: '+675'),
  CountryConfig(name: 'Paraguay', isoCode: 'PY', dialCode: '+595', nationalId: NationalIdDoc('Cédula', '1234567')),
  CountryConfig(name: 'Peru', isoCode: 'PE', dialCode: '+51', nationalId: NationalIdDoc('DNI', '12345678')),
  CountryConfig(name: 'Philippines', isoCode: 'PH', dialCode: '+63', nationalId: NationalIdDoc('PhilSys ID', '1234-5678-9012-3456')),
  CountryConfig(name: 'Poland', isoCode: 'PL', dialCode: '+48', nationalId: NationalIdDoc('Dowód osobisty (ID Card)')),
  CountryConfig(name: 'Portugal', isoCode: 'PT', dialCode: '+351', nationalId: NationalIdDoc('Cartão de Cidadão', '12345678 9 ZZ0')),
  CountryConfig(name: 'Qatar', isoCode: 'QA', dialCode: '+974', nationalId: NationalIdDoc('QID', '12345678901')),
  CountryConfig(name: 'Romania', isoCode: 'RO', dialCode: '+40', nationalId: NationalIdDoc('Carte de identitate (CNP)')),
  CountryConfig(name: 'Russia', isoCode: 'RU', dialCode: '+7', nationalId: NationalIdDoc('Internal Passport', '1234 567890')),
  CountryConfig(name: 'Rwanda', isoCode: 'RW', dialCode: '+250', nationalId: NationalIdDoc('National ID', '1234567890123456')),
  CountryConfig(name: 'Saint Kitts and Nevis', isoCode: 'KN', dialCode: '+1869'),
  CountryConfig(name: 'Saint Lucia', isoCode: 'LC', dialCode: '+1758'),
  CountryConfig(name: 'Saint Vincent and the Grenadines', isoCode: 'VC', dialCode: '+1784'),
  CountryConfig(name: 'Samoa', isoCode: 'WS', dialCode: '+685'),
  CountryConfig(name: 'San Marino', isoCode: 'SM', dialCode: '+378'),
  CountryConfig(name: 'Sao Tome and Principe', isoCode: 'ST', dialCode: '+239'),
  CountryConfig(name: 'Saudi Arabia', isoCode: 'SA', dialCode: '+966', nationalId: NationalIdDoc('National ID / Iqama', '1234567890')),
  CountryConfig(name: 'Senegal', isoCode: 'SN', dialCode: '+221', nationalId: NationalIdDoc('CNI')),
  CountryConfig(name: 'Serbia', isoCode: 'RS', dialCode: '+381', nationalId: NationalIdDoc('Lična karta (ID Card)')),
  CountryConfig(name: 'Seychelles', isoCode: 'SC', dialCode: '+248', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Sierra Leone', isoCode: 'SL', dialCode: '+232', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Singapore', isoCode: 'SG', dialCode: '+65', nationalId: NationalIdDoc('NRIC', 'S1234567A')),
  CountryConfig(name: 'Slovakia', isoCode: 'SK', dialCode: '+421', nationalId: NationalIdDoc('Občiansky preukaz (ID Card)')),
  CountryConfig(name: 'Slovenia', isoCode: 'SI', dialCode: '+386', nationalId: NationalIdDoc('Osebna izkaznica (ID Card)')),
  CountryConfig(name: 'Solomon Islands', isoCode: 'SB', dialCode: '+677'),
  CountryConfig(name: 'Somalia', isoCode: 'SO', dialCode: '+252', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'South Africa', isoCode: 'ZA', dialCode: '+27', nationalId: NationalIdDoc('Smart ID Card', '1234567890123')),
  CountryConfig(name: 'South Korea', isoCode: 'KR', dialCode: '+82', nationalId: NationalIdDoc('Resident Registration Card')),
  CountryConfig(name: 'South Sudan', isoCode: 'SS', dialCode: '+211', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Spain', isoCode: 'ES', dialCode: '+34', nationalId: NationalIdDoc('DNI', '12345678A')),
  CountryConfig(name: 'Sri Lanka', isoCode: 'LK', dialCode: '+94', nationalId: NationalIdDoc('NIC', '123456789V')),
  CountryConfig(name: 'Sudan', isoCode: 'SD', dialCode: '+249', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Suriname', isoCode: 'SR', dialCode: '+597', nationalId: NationalIdDoc('ID Card')),
  CountryConfig(name: 'Sweden', isoCode: 'SE', dialCode: '+46', nationalId: NationalIdDoc('ID-kort (National ID)')),
  CountryConfig(name: 'Switzerland', isoCode: 'CH', dialCode: '+41', nationalId: NationalIdDoc('Identitätskarte (ID Card)')),
  CountryConfig(name: 'Syria', isoCode: 'SY', dialCode: '+963', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Taiwan', isoCode: 'TW', dialCode: '+886', nationalId: NationalIdDoc('National ID Card', 'A123456789')),
  CountryConfig(name: 'Tajikistan', isoCode: 'TJ', dialCode: '+992', nationalId: NationalIdDoc('ID Card')),
  CountryConfig(name: 'Tanzania', isoCode: 'TZ', dialCode: '+255', nationalId: NationalIdDoc('NIDA ID')),
  CountryConfig(name: 'Thailand', isoCode: 'TH', dialCode: '+66', nationalId: NationalIdDoc('Thai National ID', '1-2345-67890-12-3')),
  CountryConfig(name: 'Timor-Leste', isoCode: 'TL', dialCode: '+670'),
  CountryConfig(name: 'Togo', isoCode: 'TG', dialCode: '+228', nationalId: NationalIdDoc('CNI')),
  CountryConfig(name: 'Tonga', isoCode: 'TO', dialCode: '+676'),
  CountryConfig(name: 'Trinidad and Tobago', isoCode: 'TT', dialCode: '+1868', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Tunisia', isoCode: 'TN', dialCode: '+216', nationalId: NationalIdDoc('CIN', '12345678')),
  CountryConfig(name: 'Turkey', isoCode: 'TR', dialCode: '+90', nationalId: NationalIdDoc('T.C. Kimlik Kartı', '12345678901')),
  CountryConfig(name: 'Turkmenistan', isoCode: 'TM', dialCode: '+993'),
  CountryConfig(name: 'Tuvalu', isoCode: 'TV', dialCode: '+688'),
  CountryConfig(name: 'Uganda', isoCode: 'UG', dialCode: '+256', nationalId: NationalIdDoc('National ID', 'CM12345678ABCD')),
  CountryConfig(name: 'Ukraine', isoCode: 'UA', dialCode: '+380', nationalId: NationalIdDoc('ID Card')),
  CountryConfig(name: 'United Arab Emirates', isoCode: 'AE', dialCode: '+971', nationalId: NationalIdDoc('Emirates ID', '784-1234-1234567-1')),
  CountryConfig(name: 'United Kingdom', isoCode: 'GB', dialCode: '+44'),
  CountryConfig(name: 'United States', isoCode: 'US', dialCode: '+1'),
  CountryConfig(name: 'Uruguay', isoCode: 'UY', dialCode: '+598', nationalId: NationalIdDoc('Cédula', '1.234.567-8')),
  CountryConfig(name: 'Uzbekistan', isoCode: 'UZ', dialCode: '+998', nationalId: NationalIdDoc('ID Card')),
  CountryConfig(name: 'Vanuatu', isoCode: 'VU', dialCode: '+678'),
  CountryConfig(name: 'Vatican City', isoCode: 'VA', dialCode: '+379'),
  CountryConfig(name: 'Venezuela', isoCode: 'VE', dialCode: '+58', nationalId: NationalIdDoc('Cédula', 'V-12345678')),
  CountryConfig(name: 'Vietnam', isoCode: 'VN', dialCode: '+84', nationalId: NationalIdDoc('CCCD (Citizen ID)', '123456789012')),
  CountryConfig(name: 'Yemen', isoCode: 'YE', dialCode: '+967', nationalId: NationalIdDoc('National ID')),
  CountryConfig(name: 'Zambia', isoCode: 'ZM', dialCode: '+260', nationalId: NationalIdDoc('NRC', '123456/78/9')),
  CountryConfig(name: 'Zimbabwe', isoCode: 'ZW', dialCode: '+263', nationalId: NationalIdDoc('National ID', '12-3456789A12')),
];
