// Common job titles — experience onboarding ke search suggestions ke liye.
// Sirf suggestions hain; user apna custom title bhi type kar sakta hai.
const List<String> commonJobTitles = [
  'Software Engineer',
  'Mobile App Developer',
  'Flutter Developer',
  'Web Developer',
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'UI/UX Designer',
  'Product Designer',
  'Graphic Designer',
  'Content Writer',
  'Copywriter',
  'Digital Marketer',
  'Social Media Manager',
  'SEO Specialist',
  'Data Analyst',
  'Data Scientist',
  'Machine Learning Engineer',
  'Accountant',
  'Bookkeeper',
  'Virtual Assistant',
  'Customer Support Specialist',
  'Video Editor',
  'Animator',
  'Photographer',
  'Illustrator',
  'Project Manager',
  'Product Manager',
  'Scrum Master',
  'Business Analyst',
  'QA Engineer',
  'Automation Tester',
  'DevOps Engineer',
  'Cloud Engineer',
  'System Administrator',
  'Cybersecurity Analyst',
  'Game Developer',
  'WordPress Developer',
  'Translator',
  'Voice Over Artist',
  'Sales Representative',
  'Consultant',
];
