// Duniya ki major languages — country se ALAG, globally selectable
// Nayi language add karni ho to sirf yahan entry add karo
class LanguageOption {
  final String name; // English name
  final String nativeName; // apni script mein
  final String code; // ISO 639-1 — baad mein app translations ke liye

  const LanguageOption({
    required this.name,
    required this.nativeName,
    required this.code,
  });
}

const List<LanguageOption> allLanguages = [
  LanguageOption(name: 'Amharic', nativeName: 'አማርኛ', code: 'am'),
  LanguageOption(name: 'Arabic', nativeName: 'العربية', code: 'ar'),
  LanguageOption(name: 'Azerbaijani', nativeName: 'Azərbaycanca', code: 'az'),
  LanguageOption(name: 'Bengali', nativeName: 'বাংলা', code: 'bn'),
  LanguageOption(name: 'Bulgarian', nativeName: 'Български', code: 'bg'),
  LanguageOption(name: 'Burmese', nativeName: 'မြန်မာ', code: 'my'),
  LanguageOption(name: 'Chinese (Mandarin)', nativeName: '中文', code: 'zh'),
  LanguageOption(name: 'Croatian', nativeName: 'Hrvatski', code: 'hr'),
  LanguageOption(name: 'Czech', nativeName: 'Čeština', code: 'cs'),
  LanguageOption(name: 'Danish', nativeName: 'Dansk', code: 'da'),
  LanguageOption(name: 'Dutch', nativeName: 'Nederlands', code: 'nl'),
  LanguageOption(name: 'English', nativeName: 'English', code: 'en'),
  LanguageOption(name: 'Filipino (Tagalog)', nativeName: 'Filipino', code: 'tl'),
  LanguageOption(name: 'Finnish', nativeName: 'Suomi', code: 'fi'),
  LanguageOption(name: 'French', nativeName: 'Français', code: 'fr'),
  LanguageOption(name: 'German', nativeName: 'Deutsch', code: 'de'),
  LanguageOption(name: 'Greek', nativeName: 'Ελληνικά', code: 'el'),
  LanguageOption(name: 'Gujarati', nativeName: 'ગુજરાતી', code: 'gu'),
  LanguageOption(name: 'Hausa', nativeName: 'Hausa', code: 'ha'),
  LanguageOption(name: 'Hebrew', nativeName: 'עברית', code: 'he'),
  LanguageOption(name: 'Hindi', nativeName: 'हिन्दी', code: 'hi'),
  LanguageOption(name: 'Hungarian', nativeName: 'Magyar', code: 'hu'),
  LanguageOption(name: 'Indonesian', nativeName: 'Bahasa Indonesia', code: 'id'),
  LanguageOption(name: 'Italian', nativeName: 'Italiano', code: 'it'),
  LanguageOption(name: 'Japanese', nativeName: '日本語', code: 'ja'),
  LanguageOption(name: 'Kannada', nativeName: 'ಕನ್ನಡ', code: 'kn'),
  LanguageOption(name: 'Kazakh', nativeName: 'Қазақша', code: 'kk'),
  LanguageOption(name: 'Khmer', nativeName: 'ខ្មែរ', code: 'km'),
  LanguageOption(name: 'Korean', nativeName: '한국어', code: 'ko'),
  LanguageOption(name: 'Malay', nativeName: 'Bahasa Melayu', code: 'ms'),
  LanguageOption(name: 'Malayalam', nativeName: 'മലയാളം', code: 'ml'),
  LanguageOption(name: 'Marathi', nativeName: 'मराठी', code: 'mr'),
  LanguageOption(name: 'Nepali', nativeName: 'नेपाली', code: 'ne'),
  LanguageOption(name: 'Norwegian', nativeName: 'Norsk', code: 'no'),
  LanguageOption(name: 'Pashto', nativeName: 'پښتو', code: 'ps'),
  LanguageOption(name: 'Persian (Farsi)', nativeName: 'فارسی', code: 'fa'),
  LanguageOption(name: 'Polish', nativeName: 'Polski', code: 'pl'),
  LanguageOption(name: 'Portuguese', nativeName: 'Português', code: 'pt'),
  LanguageOption(name: 'Punjabi', nativeName: 'پنجابی / ਪੰਜਾਬੀ', code: 'pa'),
  LanguageOption(name: 'Romanian', nativeName: 'Română', code: 'ro'),
  LanguageOption(name: 'Russian', nativeName: 'Русский', code: 'ru'),
  LanguageOption(name: 'Serbian', nativeName: 'Српски', code: 'sr'),
  LanguageOption(name: 'Sinhala', nativeName: 'සිංහල', code: 'si'),
  LanguageOption(name: 'Slovak', nativeName: 'Slovenčina', code: 'sk'),
  LanguageOption(name: 'Somali', nativeName: 'Soomaali', code: 'so'),
  LanguageOption(name: 'Spanish', nativeName: 'Español', code: 'es'),
  LanguageOption(name: 'Swahili', nativeName: 'Kiswahili', code: 'sw'),
  LanguageOption(name: 'Swedish', nativeName: 'Svenska', code: 'sv'),
  LanguageOption(name: 'Tamil', nativeName: 'தமிழ்', code: 'ta'),
  LanguageOption(name: 'Telugu', nativeName: 'తెలుగు', code: 'te'),
  LanguageOption(name: 'Thai', nativeName: 'ไทย', code: 'th'),
  LanguageOption(name: 'Turkish', nativeName: 'Türkçe', code: 'tr'),
  LanguageOption(name: 'Ukrainian', nativeName: 'Українська', code: 'uk'),
  LanguageOption(name: 'Urdu', nativeName: 'اردو', code: 'ur'),
  LanguageOption(name: 'Uzbek', nativeName: 'Oʻzbekcha', code: 'uz'),
  LanguageOption(name: 'Vietnamese', nativeName: 'Tiếng Việt', code: 'vi'),
  LanguageOption(name: 'Yoruba', nativeName: 'Yorùbá', code: 'yo'),
  LanguageOption(name: 'Zulu', nativeName: 'isiZulu', code: 'zu'),
];
